[package]
name = "herbatka"
version = "1.0.0"
edition = "2024"
rust-version = "1.90"
description = "A lightweight event streaming broker inspired by Apache Kafka, focused on simplicity, resilience, and fast iteration."
license = "MIT"
repository = "https://github.com/RunBerserk/herbatka"
readme = "../../README.md"
keywords = ["kafka", "broker", "messaging", "streaming", "log"]
categories = ["network-programming", "database-implementations"]

[dependencies]
herbatka-wire = { path = "../herbatka-wire" }
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread"] }
toml = "0.9"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }

[dev-dependencies]
prost = "0.13"
